/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoindividual;

import javax.swing.JOptionPane;
/**
 *
 * @author 25170626
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_limparCampo = new javax.swing.JButton();
        btn_cadastrarCliente = new javax.swing.JButton();
        input_dataNascimento = new javax.swing.JTextField();
        input_nome = new javax.swing.JTextField();
        input_cpf = new javax.swing.JTextField();
        input_telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        btn_feminino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        btn_outro = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        JLabel10 = new javax.swing.JLabel();
        input_endereco = new javax.swing.JTextField();
        endereco1 = new javax.swing.JLabel();
        input_estadoCivil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(175, 0, 31));
        jLabel1.setText("Cadastro de Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 0, 31));
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 0, 31));
        jLabel3.setText("CPF :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 0, 31));
        jLabel4.setText("Telefone :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 0, 31));
        jLabel5.setText("Email : ");

        btn_menu.setBackground(new java.awt.Color(175, 0, 31));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("←");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_limparCampo.setBackground(new java.awt.Color(102, 102, 102));
        btn_limparCampo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparCampo.setText("LIMPAR");
        btn_limparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparCampoActionPerformed(evt);
            }
        });

        btn_cadastrarCliente.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarCliente.setText("CADASTRAR");
        btn_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarClienteActionPerformed(evt);
            }
        });

        input_dataNascimento.setBackground(new java.awt.Color(204, 204, 204));
        input_dataNascimento.setText("Digite sua data de nascimento aqui");
        input_dataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_dataNascimentoFocusLost(evt);
            }
        });
        input_dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataNascimentoActionPerformed(evt);
            }
        });

        input_nome.setBackground(new java.awt.Color(204, 204, 204));
        input_nome.setText("Digite seu nome aqui");
        input_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nomeFocusLost(evt);
            }
        });
        input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nomeActionPerformed(evt);
            }
        });

        input_cpf.setBackground(new java.awt.Color(204, 204, 204));
        input_cpf.setText("Digite aqui seu CPF");
        input_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cpfFocusLost(evt);
            }
        });

        input_telefone.setBackground(new java.awt.Color(204, 204, 204));
        input_telefone.setText("Digite seu telefone aqui");
        input_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_telefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_telefoneFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 0, 31));
        jLabel7.setText("Data Nascimento:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(175, 0, 31));
        jLabel9.setText("Gênero:");

        input_email.setBackground(new java.awt.Color(204, 204, 204));
        input_email.setText("Digite seu email aqui");
        input_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_emailFocusLost(evt);
            }
        });
        input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_emailActionPerformed(evt);
            }
        });

        btn_feminino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_feminino.setForeground(new java.awt.Color(175, 0, 31));
        btn_feminino.setText("Feminino");
        btn_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femininoActionPerformed(evt);
            }
        });

        btn_masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_masculino.setForeground(new java.awt.Color(175, 0, 31));
        btn_masculino.setText("Masculino");
        btn_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masculinoActionPerformed(evt);
            }
        });

        btn_outro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_outro.setForeground(new java.awt.Color(175, 0, 31));
        btn_outro.setText("Outro");
        btn_outro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(175, 0, 31));
        jLabel6.setText("Clientes Cadastrados");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        JLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLabel10.setForeground(new java.awt.Color(175, 0, 31));
        JLabel10.setText("Endereço");

        input_endereco.setBackground(new java.awt.Color(204, 204, 204));
        input_endereco.setText("Digite seu endereço aqui");
        input_endereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_enderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_enderecoFocusLost(evt);
            }
        });
        input_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_enderecoActionPerformed(evt);
            }
        });

        endereco1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        endereco1.setForeground(new java.awt.Color(175, 0, 31));
        endereco1.setText("Estado Civil");

        input_estadoCivil.setBackground(new java.awt.Color(204, 204, 204));
        input_estadoCivil.setText("Digite seu estado civil aqui");
        input_estadoCivil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_estadoCivilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_estadoCivilFocusLost(evt);
            }
        });
        input_estadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_estadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(endereco1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_estadoCivil))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_cpf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_dataNascimento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_feminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_outro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_endereco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_cadastrarCliente)
                        .addGap(20, 20, 20)
                        .addComponent(btn_limparCampo)))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_menu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(580, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(192, 192, 192)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btn_menu)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limparCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(input_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(input_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(btn_feminino)
                            .addComponent(btn_masculino)
                            .addComponent(btn_outro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel10)
                            .addComponent(input_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endereco1)
                            .addComponent(input_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel8)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        dispose();
        new MenuOpcoes().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_limparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparCampoActionPerformed
        input_nome.setText("");
        input_cpf.setText("");
        input_telefone.setText("");
        input_email.setText("");
        input_dataNascimento.setText("");
        btn_masculino.setSelected(false);
        btn_feminino.setSelected(false);
        btn_outro.setSelected(false);
        input_endereco.setText("");
        input_estadoCivil.setText("");
    }//GEN-LAST:event_btn_limparCampoActionPerformed

    private void btn_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarClienteActionPerformed
        int valor = JOptionPane.showConfirmDialog(null, "Deseja realemente cadastrar ?", "opções", JOptionPane.YES_NO_CANCEL_OPTION);
        // yes = 0; no = 1; cancel = 2;
        if (valor == 0) {
            CadastroDoCliente c = new CadastroDoCliente();
            c.setNome(input_nome.getText());
            c.setCpf(input_cpf.getText());
            c.setTelefone(input_telefone.getText());
            c.setEmail(input_email.getText());
            c.setDataNascimento(input_dataNascimento.getText());
            if (btn_feminino.isSelected()) {
                c.setGenero("Feminino");
            }else if (btn_masculino.isSelected()){
                c.setGenero("Masculino");
            }else{
                c.setGenero("Outro");
            }
            c.setEndereco(input_endereco.getText());
            c.setEstadoCivil(input_estadoCivil.getText());

            area.setText(c.toString());
        }
    }//GEN-LAST:event_btn_cadastrarClienteActionPerformed

    private void input_dataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataNascimentoFocusGained
        // TODO add your handling code here:
        if (input_dataNascimento.getText().equals("Digite sua data de nascimento aqui")) {
            input_dataNascimento.setText("");
        }
    }//GEN-LAST:event_input_dataNascimentoFocusGained

    private void input_dataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataNascimentoFocusLost
        // TODO add your handling code here:
        if (input_dataNascimento.getText().equals("")) {
            input_dataNascimento.setText("Digite sua data de nascimento aqui");
        }
    }//GEN-LAST:event_input_dataNascimentoFocusLost

    private void input_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusGained
        if (input_nome.getText().equals("Digite seu nome aqui")) {
            input_nome.setText("");
        }
    }//GEN-LAST:event_input_nomeFocusGained

    private void input_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusLost
        // TODO add your handling code here:
        if (input_nome.getText().equals("")) {
            input_nome.setText("Digite seu nome aqui");
        }
    }//GEN-LAST:event_input_nomeFocusLost

    private void input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nomeActionPerformed

    private void input_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cpfFocusGained
        // TODO add your handling code here:
        if (input_cpf.getText().equals("Digite aqui seu CPF")) {
            input_cpf.setText("");
        }
    }//GEN-LAST:event_input_cpfFocusGained

    private void input_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cpfFocusLost
        // TODO add your handling code here:
        if (input_cpf.getText().equals("")) {
            input_cpf.setText("Digite seu CPF aqui");
        }
    }//GEN-LAST:event_input_cpfFocusLost

    private void input_telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusGained
        // TODO add your handling code here:
        if (input_telefone.getText().equals("Digite seu telefone aqui")) {
            input_telefone.setText("");
        }
    }//GEN-LAST:event_input_telefoneFocusGained

    private void input_telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusLost
        // TODO add your handling code here:
        if (input_telefone.getText().equals("")) {
            input_telefone.setText("Digite seu telefone aqui");
        }
    }//GEN-LAST:event_input_telefoneFocusLost

    private void input_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusGained
        // TODO add your handling code here:
        if (input_email.getText().equals("Digite seu email aqui")) {
            input_email.setText("");
        }
    }//GEN-LAST:event_input_emailFocusGained

    private void input_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusLost
        // TODO add your handling code here:
        if (input_email.getText().equals("")) {
            input_email.setText("Digite seu email aqui");
        }
    }//GEN-LAST:event_input_emailFocusLost

    private void btn_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femininoActionPerformed
        btn_masculino.setSelected(false);
        btn_outro.setSelected(false);
    }//GEN-LAST:event_btn_femininoActionPerformed

    private void btn_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masculinoActionPerformed
        btn_outro.setSelected(false);
        btn_feminino.setSelected(false);
    }//GEN-LAST:event_btn_masculinoActionPerformed

    private void btn_outroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outroActionPerformed
        btn_masculino.setSelected(false);
        btn_feminino.setSelected(false);
    }//GEN-LAST:event_btn_outroActionPerformed

    private void input_dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_dataNascimentoActionPerformed

    private void input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_emailActionPerformed

    private void input_enderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_enderecoFocusGained
        // TODO add your handling code here:
        if (input_endereco.getText().equals("Digite seu endereço aqui")) {
            input_endereco.setText("");
        }
    }//GEN-LAST:event_input_enderecoFocusGained

    private void input_enderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_enderecoFocusLost
        // TODO add your handling code here:
        if (input_endereco.getText().equals("")) {
            input_endereco.setText("Digite seu endereço aqui");
        }
        
    }//GEN-LAST:event_input_enderecoFocusLost

    private void input_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_enderecoActionPerformed

    private void input_estadoCivilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_estadoCivilFocusGained
        // TODO add your handling code here:
        if (input_estadoCivil.getText().equals("Digite seu estado civil aqui")) {
            input_estadoCivil.setText("");
        }
    }//GEN-LAST:event_input_estadoCivilFocusGained

    private void input_estadoCivilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_estadoCivilFocusLost
        // TODO add your handling code here:
        if (input_estadoCivil.getText().equals("")) {
            input_estadoCivil.setText("Digite seu estado civil aqui");
        }
    }//GEN-LAST:event_input_estadoCivilFocusLost

    private void input_estadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_estadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_estadoCivilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel10;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_cadastrarCliente;
    private javax.swing.JRadioButton btn_feminino;
    private javax.swing.JButton btn_limparCampo;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JButton btn_menu;
    private javax.swing.JRadioButton btn_outro;
    private javax.swing.JLabel endereco1;
    private javax.swing.JTextField input_cpf;
    private javax.swing.JTextField input_dataNascimento;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_endereco;
    private javax.swing.JTextField input_estadoCivil;
    private javax.swing.JTextField input_nome;
    private javax.swing.JTextField input_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
