/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoindividual;

import javax.swing.JOptionPane;
/**
 *
 * @author 25170626
 */
public class Corretor extends javax.swing.JFrame {

    /**
     * Creates new form Corretor
     */
    public Corretor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_limparCampo = new javax.swing.JButton();
        btn_cadastrarCorretor = new javax.swing.JButton();
        input_email = new javax.swing.JTextField();
        input_nome = new javax.swing.JTextField();
        input_creci = new javax.swing.JTextField();
        input_telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_especialidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        input_dataAdmissao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        input_comissao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(175, 0, 31));
        jLabel1.setText("Cadastro de Corretores");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 0, 31));
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 0, 31));
        jLabel3.setText("Creci :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 0, 31));
        jLabel4.setText("Telefone :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 0, 31));
        jLabel5.setText("Email : ");

        btn_menu.setBackground(new java.awt.Color(175, 0, 31));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("←");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_limparCampo.setBackground(new java.awt.Color(102, 102, 102));
        btn_limparCampo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparCampo.setText("LIMPAR");
        btn_limparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparCampoActionPerformed(evt);
            }
        });

        btn_cadastrarCorretor.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastrarCorretor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarCorretor.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarCorretor.setText("CADASTRAR");
        btn_cadastrarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarCorretorActionPerformed(evt);
            }
        });

        input_email.setBackground(new java.awt.Color(204, 204, 204));
        input_email.setText("Digite seu email aqui...");
        input_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_emailFocusLost(evt);
            }
        });

        input_nome.setBackground(new java.awt.Color(204, 204, 204));
        input_nome.setText("Digite seu nome aqui...");
        input_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nomeFocusLost(evt);
            }
        });
        input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nomeActionPerformed(evt);
            }
        });

        input_creci.setBackground(new java.awt.Color(204, 204, 204));
        input_creci.setText("Digite seu creci aqui...");
        input_creci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_creciFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_creciFocusLost(evt);
            }
        });

        input_telefone.setBackground(new java.awt.Color(204, 204, 204));
        input_telefone.setText("Digite seu telefone aqui...");
        input_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_telefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_telefoneFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 0, 31));
        jLabel7.setText("Especialidade:");

        input_especialidade.setBackground(new java.awt.Color(204, 204, 204));
        input_especialidade.setText("Digite sua especialidade aqui...");
        input_especialidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_especialidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_especialidadeFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(175, 0, 31));
        jLabel8.setText("Data Admissão:");

        input_dataAdmissao.setBackground(new java.awt.Color(204, 204, 204));
        input_dataAdmissao.setText("Digite sua data de admissao aqui...");
        input_dataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataAdmissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_dataAdmissaoFocusLost(evt);
            }
        });
        input_dataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataAdmissaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(175, 0, 31));
        jLabel6.setText("Corretores Cadastrados");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(175, 0, 31));
        jLabel9.setText("Comissao:");

        input_comissao.setBackground(new java.awt.Color(204, 204, 204));
        input_comissao.setText("Digite sua comissão aqui");
        input_comissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_comissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_comissaoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_dataAdmissao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_creci))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_comissao)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_cadastrarCorretor)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limparCampo)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_menu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addComponent(btn_menu))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input_creci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(input_dataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(input_comissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limparCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        dispose();
        new MenuOpcoes().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_limparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparCampoActionPerformed
        // TODO add your handling code here:
        input_nome.setText("");
        input_creci.setText("");
        input_telefone.setText("");
        input_email.setText("");
        input_dataAdmissao.setText("");
        input_especialidade.setText("");
        input_comissao.setText("");
    }//GEN-LAST:event_btn_limparCampoActionPerformed

    private void btn_cadastrarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarCorretorActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Deseja realemente cadastrar ?", "opções", JOptionPane.YES_NO_CANCEL_OPTION);
        // yes = 0; no = 1; cancel = 2;
        if (valor == 0) {
            CadastroDeCorretores c = new CadastroDeCorretores();
            c.setNome(input_nome.getText());
            c.setCreci(input_creci.getText());
            c.setTelefone(input_telefone.getText());
            c.setEmail(input_email.getText());
            c.setDataAdmissao(input_dataAdmissao.getText());
            c.setEspecialidade(input_especialidade.getText());
            c.setComissao(input_comissao.getText());

            area.setText(c.toString());
        }
    }//GEN-LAST:event_btn_cadastrarCorretorActionPerformed

    private void input_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusGained
        // TODO add your handling code here:
        if (input_email.getText().equals("Digite seu email aqui...")) {
            input_email.setText("");
        }
    }//GEN-LAST:event_input_emailFocusGained

    private void input_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusLost
        // TODO add your handling code here:
        if (input_email.getText().equals("")) {
            input_email.setText("Digite seu email aqui...");
        }
    }//GEN-LAST:event_input_emailFocusLost

    private void input_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusGained
        // TODO add your handling code here:
        if (input_nome.getText().equals("Digite seu nome aqui...")) {
            input_nome.setText("");
        }
    }//GEN-LAST:event_input_nomeFocusGained

    private void input_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusLost
        // TODO add your handling code here:
        if (input_nome.getText().equals("")) {
            input_nome.setText("Digite seu nome aqui...");
        }
    }//GEN-LAST:event_input_nomeFocusLost

    private void input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nomeActionPerformed

    private void input_creciFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_creciFocusGained
        // TODO add your handling code here:
        if (input_creci.getText().equals("Digite seu creci aqui...")) {
            input_creci.setText("");
        }
    }//GEN-LAST:event_input_creciFocusGained

    private void input_creciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_creciFocusLost
        // TODO add your handling code here:
        if (input_creci.getText().equals("")) {
            input_creci.setText("Digite seu creci aqui...");
        }
    }//GEN-LAST:event_input_creciFocusLost

    private void input_telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusGained
        // TODO add your handling code here:
        if (input_telefone.getText().equals("Digite seu telefone aqui...")) {
            input_telefone.setText("");
        }
    }//GEN-LAST:event_input_telefoneFocusGained

    private void input_telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusLost
        // TODO add your handling code here:
        if (input_telefone.getText().equals("")) {
            input_telefone.setText("Digite seu telefone aqui...");
        }
    }//GEN-LAST:event_input_telefoneFocusLost

    private void input_especialidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_especialidadeFocusGained
        // TODO add your handling code here:
        if (input_especialidade.getText().equals("Digite sua especialidade aqui...")) {
            input_especialidade.setText("");
        }
    }//GEN-LAST:event_input_especialidadeFocusGained

    private void input_especialidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_especialidadeFocusLost
        // TODO add your handling code here:
        if (input_especialidade.getText().equals("")) {
            input_especialidade.setText("Digite sua especialidade aqui...");
        }
    }//GEN-LAST:event_input_especialidadeFocusLost

    private void input_dataAdmissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataAdmissaoFocusGained
        // TODO add your handling code here:
        if (input_dataAdmissao.getText().equals("Digite sua data de admissao aqui...")) {
            input_dataAdmissao.setText("");
        }
    }//GEN-LAST:event_input_dataAdmissaoFocusGained

    private void input_dataAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataAdmissaoFocusLost
        // TODO add your handling code here:
        if (input_dataAdmissao.getText().equals("")) {
            input_dataAdmissao.setText("Digite sua data de admissao aqui...");
        }
    }//GEN-LAST:event_input_dataAdmissaoFocusLost

    private void input_dataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_dataAdmissaoActionPerformed

    private void input_comissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_comissaoFocusGained
        // TODO add your handling code here:
        if (input_comissao.getText().equals("Digite sua comissão aqui")) {
            input_comissao.setText("");
        }
    }//GEN-LAST:event_input_comissaoFocusGained

    private void input_comissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_comissaoFocusLost
        // TODO add your handling code here:
        if (input_comissao.getText().equals("")) {
            input_comissao.setText("Digite sua comissão aqui");
        }
    }//GEN-LAST:event_input_comissaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_cadastrarCorretor;
    private javax.swing.JButton btn_limparCampo;
    private javax.swing.JButton btn_menu;
    private javax.swing.JTextField input_comissao;
    private javax.swing.JTextField input_creci;
    private javax.swing.JTextField input_dataAdmissao;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_especialidade;
    private javax.swing.JTextField input_nome;
    private javax.swing.JTextField input_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
