/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoindividual;

import javax.swing.JOptionPane;

/**
 *
 * @author 25170626
 */
public class Locacao extends javax.swing.JFrame {

    /**
     * Creates new form Locacao
     */
    public Locacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_limparCampo = new javax.swing.JButton();
        btn_cadastrarCliente = new javax.swing.JButton();
        input_dataInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        input_dataFim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_valorLocacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        select_imovel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        select_locatario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        select_corretor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(175, 0, 31));
        jLabel1.setText("Locação de Imovéis");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 0, 31));
        jLabel2.setText("Data Inicio: ");

        btn_menu.setBackground(new java.awt.Color(175, 0, 31));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("VOLTAR");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_limparCampo.setBackground(new java.awt.Color(102, 102, 102));
        btn_limparCampo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparCampo.setText("CANCELAR");
        btn_limparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparCampoActionPerformed(evt);
            }
        });

        btn_cadastrarCliente.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarCliente.setText("CADASTRAR");
        btn_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarClienteActionPerformed(evt);
            }
        });

        input_dataInicio.setBackground(new java.awt.Color(204, 204, 204));
        input_dataInicio.setText("Digite a data de inicio aqui...");
        input_dataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_dataInicioFocusLost(evt);
            }
        });
        input_dataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataInicioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 0, 31));
        jLabel3.setText("Data Fim: ");

        input_dataFim.setBackground(new java.awt.Color(204, 204, 204));
        input_dataFim.setText("Digite a data de fim aqui...");
        input_dataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_dataFimFocusLost(evt);
            }
        });
        input_dataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataFimActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 0, 31));
        jLabel4.setText("Valor Mensal:");

        input_valorLocacao.setBackground(new java.awt.Color(204, 204, 204));
        input_valorLocacao.setText("Digite o valor da locacao aqui...");
        input_valorLocacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_valorLocacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_valorLocacaoFocusLost(evt);
            }
        });
        input_valorLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_valorLocacaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 0, 31));
        jLabel5.setText("Imovél: ");

        select_imovel.setBackground(new java.awt.Color(204, 204, 204));
        select_imovel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        select_imovel.setForeground(new java.awt.Color(175, 0, 31));
        select_imovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imovel 1", "Imovel 2", "Imovel 3", "Imovel 4", "Imovel 5", "Imovel 6", "Imovel 7", "Imovel 8", "Imovel 9", "Imovel 10" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 0, 31));
        jLabel7.setText("Locatário:");

        select_locatario.setBackground(new java.awt.Color(204, 204, 204));
        select_locatario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        select_locatario.setForeground(new java.awt.Color(175, 0, 31));
        select_locatario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ana Paula Souza", "Carlos Eduardo Lima", "Juliana Mendes", "Bruno Rocha", "Mariana Ferreira", "Lucas Martins", "Fernanda Dias", "Rodrigo Alves", "Patrícia Gomes", "Thiago Santana" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(175, 0, 31));
        jLabel9.setText("Corretor:");

        select_corretor.setBackground(new java.awt.Color(204, 204, 204));
        select_corretor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        select_corretor.setForeground(new java.awt.Color(175, 0, 31));
        select_corretor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João Oliveira", "Renata Lima", "Felipe Silva", "Luciana Mendes", "Gabriel Costa", "Isabela Moreira", "Roberto Souza", "Camila Ribeiro", "Daniel Freitas", "Elaine Martins" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(175, 0, 31));
        jLabel6.setText("Imovéis Alugados");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_dataFim))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_valorLocacao))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(select_locatario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(select_imovel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(select_corretor, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(2, 2, 2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cadastrarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btn_limparCampo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_menu)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_menu)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(input_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(input_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(input_valorLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(select_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(select_locatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(select_corretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_limparCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        dispose();
        new MenuOpcoes().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_limparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparCampoActionPerformed
        // TODO add your handling code here:
        input_dataInicio.setText("");
        input_dataFim.setText("");
        input_valorLocacao.setText("");
        select_imovel.setSelectedIndex(0);
        select_locatario.setSelectedIndex(0);
        select_corretor.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limparCampoActionPerformed

    private void btn_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarClienteActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Deseja realemente cadastrar Imovel ?", "opções", JOptionPane.YES_NO_CANCEL_OPTION);

        // yes = 0; no = 1; cancel = 2;
        if (valor == 0) {

            CadastroDeLocacao l = new CadastroDeLocacao();

            l.setDataInicio(input_dataInicio.getText());
            l.setDataFim(input_dataFim.getText());
            l.setValor(input_valorLocacao.getText());
            l.setImovel((String) select_imovel.getSelectedItem());
            l.setLocatario((String) select_locatario.getSelectedItem());
            l.setCorretor((String) select_corretor.getSelectedItem());

            area.setText(l.toString());
        }
    }//GEN-LAST:event_btn_cadastrarClienteActionPerformed

    private void input_dataInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataInicioFocusGained
        // TODO add your handling code here:
        if (input_dataInicio.getText().equals("Digite a data de inicio aqui...")) {
            input_dataInicio.setText("");
        }
    }//GEN-LAST:event_input_dataInicioFocusGained

    private void input_dataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataInicioFocusLost
        // TODO add your handling code here:
        if (input_dataInicio.getText().equals("")) {
            input_dataInicio.setText("Digite a data de inicio aqui...");
        }
    }//GEN-LAST:event_input_dataInicioFocusLost

    private void input_dataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_dataInicioActionPerformed

    private void input_dataFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataFimFocusGained
        // TODO add your handling code here:
        if (input_dataFim.getText().equals("Digite a data de fim aqui...")) {
            input_dataFim.setText("");
        }
    }//GEN-LAST:event_input_dataFimFocusGained

    private void input_dataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataFimFocusLost
        // TODO add your handling code here:
        if (input_dataFim.getText().equals("")) {
            input_dataFim.setText("Digite a data de fim aqui...");
        }
    }//GEN-LAST:event_input_dataFimFocusLost

    private void input_dataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_dataFimActionPerformed

    private void input_valorLocacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_valorLocacaoFocusGained
        // TODO add your handling code here:
        if (input_valorLocacao.getText().equals("Digite o valor da locacao aqui...")) {
            input_valorLocacao.setText("");
        }
    }//GEN-LAST:event_input_valorLocacaoFocusGained

    private void input_valorLocacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_valorLocacaoFocusLost
        // TODO add your handling code here:
        if (input_valorLocacao.getText().equals("")) {
            input_valorLocacao.setText("Digite o valor da locacao aqui...");
        }
    }//GEN-LAST:event_input_valorLocacaoFocusLost

    private void input_valorLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_valorLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_valorLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Locacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_cadastrarCliente;
    private javax.swing.JButton btn_limparCampo;
    private javax.swing.JButton btn_menu;
    private javax.swing.JTextField input_dataFim;
    private javax.swing.JTextField input_dataInicio;
    private javax.swing.JTextField input_valorLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> select_corretor;
    private javax.swing.JComboBox<String> select_imovel;
    private javax.swing.JComboBox<String> select_locatario;
    // End of variables declaration//GEN-END:variables
}
