/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoindividual;

/**
 *
 * @author 25170626
 */
public class MenuOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpcoes
     */
    public MenuOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cadastroCliente = new javax.swing.JButton();
        btn_cadastroCorretor = new javax.swing.JButton();
        btn_cadastroTipoImovel = new javax.swing.JButton();
        btn_cadastroProrietario = new javax.swing.JButton();
        btn_cadastroImoveis = new javax.swing.JButton();
        btn_cadastroLocacao = new javax.swing.JButton();
        btn_cadastroVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        btn_cadastroCliente.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroCliente.setText("Cadastro Cliente");
        btn_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroClienteActionPerformed(evt);
            }
        });

        btn_cadastroCorretor.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroCorretor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroCorretor.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroCorretor.setText("Cadastro Corretores");
        btn_cadastroCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroCorretorActionPerformed(evt);
            }
        });

        btn_cadastroTipoImovel.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroTipoImovel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroTipoImovel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroTipoImovel.setText("Cadastro Tipo de Imoveis");
        btn_cadastroTipoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroTipoImovelActionPerformed(evt);
            }
        });

        btn_cadastroProrietario.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroProrietario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroProrietario.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroProrietario.setText("Cadastro Proprietarios");
        btn_cadastroProrietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroProrietarioActionPerformed(evt);
            }
        });

        btn_cadastroImoveis.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroImoveis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroImoveis.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroImoveis.setText("Cadastro Imoveis");
        btn_cadastroImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroImoveisActionPerformed(evt);
            }
        });

        btn_cadastroLocacao.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroLocacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroLocacao.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroLocacao.setText("Cadastro Locação");
        btn_cadastroLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroLocacaoActionPerformed(evt);
            }
        });

        btn_cadastroVenda.setBackground(new java.awt.Color(175, 0, 31));
        btn_cadastroVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastroVenda.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastroVenda.setText("Cadastro Venda");
        btn_cadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(btn_cadastroCorretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastroTipoImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastroProrietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastroImoveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastroLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(btn_cadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastroCorretor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastroTipoImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastroProrietario)
                .addGap(12, 12, 12)
                .addComponent(btn_cadastroImoveis)
                .addGap(12, 12, 12)
                .addComponent(btn_cadastroLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastroVenda)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroClienteActionPerformed
        dispose();
        new Cliente().setVisible(true);
    }//GEN-LAST:event_btn_cadastroClienteActionPerformed

    private void btn_cadastroCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroCorretorActionPerformed
        dispose();
        new Corretor().setVisible(true);
    }//GEN-LAST:event_btn_cadastroCorretorActionPerformed

    private void btn_cadastroTipoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroTipoImovelActionPerformed
        dispose();
        new TipoImoveis().setVisible(true);
    }//GEN-LAST:event_btn_cadastroTipoImovelActionPerformed

    private void btn_cadastroProrietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroProrietarioActionPerformed
        dispose();
        new Proprietario2().setVisible(true);
    }//GEN-LAST:event_btn_cadastroProrietarioActionPerformed

    private void btn_cadastroImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroImoveisActionPerformed
        dispose();
        new Imovel2().setVisible(true);
    }//GEN-LAST:event_btn_cadastroImoveisActionPerformed

    private void btn_cadastroLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroLocacaoActionPerformed
        dispose();
        new Locacao().setVisible(true);
    }//GEN-LAST:event_btn_cadastroLocacaoActionPerformed

    private void btn_cadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroVendaActionPerformed
        dispose();
        new Venda().setVisible(true);
    }//GEN-LAST:event_btn_cadastroVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastroCliente;
    private javax.swing.JButton btn_cadastroCorretor;
    private javax.swing.JButton btn_cadastroImoveis;
    private javax.swing.JButton btn_cadastroLocacao;
    private javax.swing.JButton btn_cadastroProrietario;
    private javax.swing.JButton btn_cadastroTipoImovel;
    private javax.swing.JButton btn_cadastroVenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
