/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoindividual;

import javax.swing.JOptionPane;

/**
 *
 * @author 25170626
 */
public class Proprietario2 extends javax.swing.JFrame {

    /**
     * Creates new form prop2
     */
    public Proprietario2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_limparCampo = new javax.swing.JButton();
        btn_cadastrarCliente = new javax.swing.JButton();
        input_dataNascimento = new javax.swing.JTextField();
        input_nome = new javax.swing.JTextField();
        input_cpf = new javax.swing.JTextField();
        input_telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        btn_feminino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        btn_outro = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btn_menu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        input_profissao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        input_nacionalidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(175, 0, 31));
        jLabel1.setText("Cadastro de Proprietários");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 39, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 0, 31));
        jLabel2.setText("Nome :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 83, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 0, 31));
        jLabel3.setText("CPF :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 0, 31));
        jLabel4.setText("Telefone :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 163, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(175, 0, 31));
        jLabel5.setText("Email : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 203, -1, -1));

        btn_limparCampo.setBackground(new java.awt.Color(102, 102, 102));
        btn_limparCampo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparCampo.setText("LIMPAR");
        btn_limparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparCampoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limparCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 307, -1, 35));

        btn_cadastrarCliente.setBackground(new java.awt.Color(153, 0, 0));
        btn_cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarCliente.setText("CADASTRAR");
        btn_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 307, -1, 35));

        input_dataNascimento.setBackground(new java.awt.Color(204, 204, 204));
        input_dataNascimento.setText("Digite sua data de nascimento aqui...");
        input_dataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_dataNascimentoFocusLost(evt);
            }
        });
        input_dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(input_dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 239, -1, -1));

        input_nome.setBackground(new java.awt.Color(204, 204, 204));
        input_nome.setText("Digite seu nome aqui...");
        input_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nomeFocusLost(evt);
            }
        });
        input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nomeActionPerformed(evt);
            }
        });
        jPanel1.add(input_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 85, 303, -1));

        input_cpf.setBackground(new java.awt.Color(204, 204, 204));
        input_cpf.setText("Digite seu CPF aqui...");
        input_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cpfFocusLost(evt);
            }
        });
        jPanel1.add(input_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 125, 323, -1));

        input_telefone.setBackground(new java.awt.Color(204, 204, 204));
        input_telefone.setText("Digite seu telefone aqui...");
        input_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_telefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_telefoneFocusLost(evt);
            }
        });
        jPanel1.add(input_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 165, 258, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 0, 31));
        jLabel7.setText("Data Nascimento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 237, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(175, 0, 31));
        jLabel9.setText("Gênero:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 271, -1, -1));

        input_email.setBackground(new java.awt.Color(204, 204, 204));
        input_email.setText("Digite seu email aqui...");
        input_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_emailFocusLost(evt);
            }
        });
        jPanel1.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 205, 303, -1));

        btn_feminino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_feminino.setForeground(new java.awt.Color(175, 0, 31));
        btn_feminino.setText("Feminino");
        btn_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femininoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 276, -1, -1));

        btn_masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_masculino.setForeground(new java.awt.Color(175, 0, 31));
        btn_masculino.setText("Masculino");
        btn_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masculinoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 276, -1, -1));

        btn_outro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_outro.setForeground(new java.awt.Color(175, 0, 31));
        btn_outro.setText("Outro");
        btn_outro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_outro, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 276, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(175, 0, 31));
        jLabel6.setText("Proprietários Cadastrados");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 56, -1, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 215, -1, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 93, -1, 204));

        btn_menu.setBackground(new java.awt.Color(153, 0, 0));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("←");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 27));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(175, 0, 31));
        jLabel10.setText("Nacionalidade:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 341, -1, -1));

        input_profissao.setBackground(new java.awt.Color(204, 204, 204));
        input_profissao.setText("Digite sua profissão aqui");
        input_profissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_profissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_profissaoFocusLost(evt);
            }
        });
        jPanel1.add(input_profissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 309, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(175, 0, 31));
        jLabel11.setText("Profissão");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 307, -1, -1));

        input_nacionalidade.setBackground(new java.awt.Color(204, 204, 204));
        input_nacionalidade.setText("Digite sua nacionalidade aqui");
        input_nacionalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nacionalidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nacionalidadeFocusLost(evt);
            }
        });
        jPanel1.add(input_nacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 343, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparCampoActionPerformed
        // TODO add your handling code here:
        input_nome.setText("");
        input_cpf.setText("");
        input_telefone.setText("");
        input_email.setText("");
        input_dataNascimento.setText("");
        btn_masculino.setSelected(false);
        btn_feminino.setSelected(false);
        btn_outro.setSelected(false);
        input_profissao.setText("");
        input_nacionalidade.setText("");
    }//GEN-LAST:event_btn_limparCampoActionPerformed

    private void btn_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarClienteActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Deseja realemente cadastrar ?", "opções", JOptionPane.YES_NO_CANCEL_OPTION);
        // yes = 0; no = 1; cancel = 2;
        if (valor == 0) {
            CadastroDoProprietario p = new CadastroDoProprietario();
            p.setNome(input_nome.getText());
            p.setCpf(input_cpf.getText());
            p.setTelefone(input_telefone.getText());
            p.setEmail(input_email.getText());
            p.setDataNascimento(input_dataNascimento.getText());
            if (btn_feminino.isSelected()) {
                p.setGenero("Feminino");
            }else if (btn_masculino.isSelected()){
                p.setGenero("Masculino");
            }else{
                p.setGenero("Outro");
            }
            p.setProfissao(input_profissao.getText());
            p.setNacionalidade(input_nacionalidade.getText());

            area.setText(p.toString());
        }
    }//GEN-LAST:event_btn_cadastrarClienteActionPerformed

    private void input_dataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataNascimentoFocusGained
        // TODO add your handling code here:
        if (input_dataNascimento.getText().equals("Digite sua data de nascimento aqui...")) {
            input_dataNascimento.setText("");
        }
    }//GEN-LAST:event_input_dataNascimentoFocusGained

    private void input_dataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataNascimentoFocusLost
        // TODO add your handling code here:
        if (input_dataNascimento.getText().equals("")) {
            input_dataNascimento.setText("Digite sua data de nascimento aqui...");
        }
    }//GEN-LAST:event_input_dataNascimentoFocusLost

    private void input_dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_dataNascimentoActionPerformed

    private void input_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusGained
        // TODO add your handling code here:
        if (input_nome.getText().equals("Digite seu nome aqui...")) {
            input_nome.setText("");
        }
    }//GEN-LAST:event_input_nomeFocusGained

    private void input_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nomeFocusLost
        // TODO add your handling code here:
        if (input_nome.getText().equals("")) {
            input_nome.setText("Digite seu nome aqui...");
        }
    }//GEN-LAST:event_input_nomeFocusLost

    private void input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nomeActionPerformed

    private void input_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cpfFocusGained
        // TODO add your handling code here:
        if (input_cpf.getText().equals("Digite seu CPF aqui...")) {
            input_cpf.setText("");
        }
    }//GEN-LAST:event_input_cpfFocusGained

    private void input_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cpfFocusLost
        // TODO add your handling code here:
        if (input_cpf.getText().equals("")) {
            input_cpf.setText("Digite seu CPF aqui...");
        }
    }//GEN-LAST:event_input_cpfFocusLost

    private void input_telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusGained
        // TODO add your handling code here:
        if (input_telefone.getText().equals("Digite seu telefone aqui...")) {
            input_telefone.setText("");
        }
    }//GEN-LAST:event_input_telefoneFocusGained

    private void input_telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefoneFocusLost
        // TODO add your handling code here:
        if (input_telefone.getText().equals("")) {
            input_telefone.setText("Digite seu telefone aqui...");
        }
    }//GEN-LAST:event_input_telefoneFocusLost

    private void input_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusGained
        // TODO add your handling code here:
        if (input_email.getText().equals("Digite seu email aqui...")) {
            input_email.setText("");
        }
    }//GEN-LAST:event_input_emailFocusGained

    private void input_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusLost
        // TODO add your handling code here:
        if (input_email.getText().equals("")) {
            input_email.setText("Digite seu email aqui...");
        }
    }//GEN-LAST:event_input_emailFocusLost

    private void btn_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femininoActionPerformed
        // TODO add your handling code here:
        btn_masculino.setSelected(false);
        btn_outro.setSelected(false);
    }//GEN-LAST:event_btn_femininoActionPerformed

    private void btn_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masculinoActionPerformed
        // TODO add your handling code here:
        btn_feminino.setSelected(false);
        btn_outro.setSelected(false);
    }//GEN-LAST:event_btn_masculinoActionPerformed

    private void btn_outroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outroActionPerformed
        // TODO add your handling code here:
        btn_feminino.setSelected(false);
        btn_masculino.setSelected(false);
    }//GEN-LAST:event_btn_outroActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        dispose();
        new MenuOpcoes().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void input_profissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_profissaoFocusGained
        // TODO add your handling code here:
        if (input_profissao.getText().equals("Digite sua profissão aqui")) {
            input_profissao.setText("");
        }
    }//GEN-LAST:event_input_profissaoFocusGained

    private void input_profissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_profissaoFocusLost
        // TODO add your handling code here:
        if (input_profissao.getText().equals("")) {
            input_profissao.setText("Digite sua profissão aqui");
        }
    }//GEN-LAST:event_input_profissaoFocusLost

    private void input_nacionalidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nacionalidadeFocusGained
        // TODO add your handling code here:
        if (input_nacionalidade.getText().equals("Digite sua nacionalidade aqui")) {
            input_nacionalidade.setText("");
        }
    }//GEN-LAST:event_input_nacionalidadeFocusGained

    private void input_nacionalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nacionalidadeFocusLost
        // TODO add your handling code here:
        if (input_nacionalidade.getText().equals("")) {
            input_nacionalidade.setText("Digite sua nacionalidade aqui");
        }
    }//GEN-LAST:event_input_nacionalidadeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proprietario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proprietario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proprietario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proprietario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proprietario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_cadastrarCliente;
    private javax.swing.JRadioButton btn_feminino;
    private javax.swing.JButton btn_limparCampo;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JButton btn_menu;
    private javax.swing.JRadioButton btn_outro;
    private javax.swing.JTextField input_cpf;
    private javax.swing.JTextField input_dataNascimento;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nacionalidade;
    private javax.swing.JTextField input_nome;
    private javax.swing.JTextField input_profissao;
    private javax.swing.JTextField input_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
